const fs = require('fs');

const data = {
    sports: {
        A: ['archery', 'athletics', 'aerobics', 'arm wrestling'],
        B: ['basketball', 'baseball', 'badminton', 'boxing', 'bowling'],
        C: ['cricket', 'cycling', 'climbing', 'curling'],
        D: ['diving', 'discus'],
        E: ['equestrian'],
        F: ['football', 'fencing', 'field hockey'],
        G: ['golf', 'gymnastics'],
        H: ['hockey', 'handball', 'hurdles', 'high jump'],
        I: ['ice hockey', 'ice skating'],
        J: ['javelin', 'judo'],
        K: ['karate', 'kayaking'],
        L: ['lacrosse', 'long jump'],
        M: ['marathon', 'martial arts'],
        N: ['netball'],
        O: ['orienteering'],
        P: ['polo', 'powerlifting', 'pole vault'],
        Q: ['quidditch'],
        R: ['rugby', 'rowing', 'running'],
        S: ['soccer', 'swimming', 'surfing', 'skateboarding', 'skiing', 'squash', 'snooker', 'softball'],
        T: ['tennis', 'taekwondo', 'table tennis', 'triathlon'],
        U: ['ultimate frisbee'],
        V: ['volleyball'],
        W: ['wrestling', 'weightlifting', 'water polo'],
        X: ['xcross'],
        Y: ['yoga'],
        Z: ['zumba'],
    },
    brands: {
        A: ['apple', 'adidas', 'amazon', 'audi', 'airbnb', 'adobe', 'asus', 'alibaba'],
        B: ['bmw', 'boeing', 'burberry', 'beats', 'blackberry', 'bugatti'],
        C: ['canon', 'coca cola', 'chevrolet', 'chanel', 'cisco'],
        D: ['dell', 'disney', 'dior', 'ducati'],
        E: ['ebay', 'esprit'],
        F: ['ford', 'ferrari', 'facebook', 'fendi'],
        G: ['google', 'gucci', 'gap', 'gillette'],
        H: ['honda', 'huawei', 'hp', 'hermes', 'hyundai'],
        I: ['ikea', 'intel', 'instagram'],
        J: ['jaguar', 'jeep'],
        K: ['kia', 'kodak'],
        L: ['lg', 'lamborghini', 'levis', 'lenovo', 'loreal'],
        M: ['microsoft', 'mercedes', 'motorola', 'mcdonalds'],
        N: ['nike', 'nintendo', 'netflix', 'nokia'],
        O: ['oppo', 'oracle'],
        P: ['pepsi', 'porsche', 'puma', 'philips'],
        Q: ['qualcomm'],
        R: ['rolex', 'realme', 'rolls royce'],
        S: ['samsung', 'sony', 'spotify', 'snapchat'],
        T: ['tesla', 'toyota', 'twitter', 'tiktok'],
        U: ['uber', 'under armour'],
        V: ['visa', 'vivo', 'volkswagen'],
        W: ['walmart', 'whatsapp'],
        X: ['xiaomi', 'xbox'],
        Y: ['yahoo', 'youtube', 'yamaha'],
        Z: ['zara', 'zoom'],
    },
    vegetables: {
        A: ['artichoke', 'asparagus', 'arugula'],
        B: ['broccoli', 'brussels sprout', 'beetroot', 'bok choy', 'bitter gourd'],
        C: ['carrot', 'cabbage', 'cauliflower', 'celery', 'capsicum', 'corn', 'cucumber'],
        D: ['drumstick'],
        E: ['eggplant'],
        F: ['fennel'],
        G: ['garlic', 'ginger', 'green bean', 'green onion'],
        H: ['horseradish'],
        I: ['iceberg lettuce'],
        J: ['jalapeno'],
        K: ['kale', 'kohlrabi'],
        L: ['leek', 'lettuce'],
        M: ['mushroom', 'mint'],
        N: ['neem'],
        O: ['onion', 'okra'],
        P: ['potato', 'pumpkin', 'peas', 'parsley', 'pepper'],
        Q: ['quinoa'],
        R: ['radish', 'rhubarb'],
        S: ['spinach', 'sweet potato', 'spring onion'],
        T: ['tomato', 'turnip', 'taro'],
        U: ['ulluco'],
        V: ['valerian'],
        W: ['watercress'],
        X: ['xigua'],
        Y: ['yam'],
        Z: ['zucchini'],
    },
    fruits: {
        A: ['apple', 'avocado', 'apricot', 'almond'],
        B: ['banana', 'blueberry', 'blackberry'],
        C: ['cherry', 'coconut', 'cranberry', 'custard apple'],
        D: ['date', 'dragonfruit'],
        E: ['elderberry'],
        F: ['fig'],
        G: ['grape', 'guava'],
        H: ['honeydew'],
        I: ['indian gooseberry'],
        J: ['jackfruit'],
        K: ['kiwi'],
        L: ['lemon', 'litchi', 'lime'],
        M: ['mango', 'melon', 'mulberry'],
        N: ['nectarine'],
        O: ['orange', 'olive'],
        P: ['peach', 'pear', 'pineapple', 'pomegranate', 'plum', 'papaya'],
        Q: ['quince'],
        R: ['raspberry'],
        S: ['strawberry', 'starfruit'],
        T: ['tangerine', 'tamarind'],
        U: ['ugli fruit'],
        V: ['vanilla'],
        W: ['watermelon'],
        X: ['ximenia'],
        Y: ['yuzu'],
        Z: ['ziziphus'],
    },
    colors: {
        A: ['amber', 'aqua', 'azure'],
        B: ['black', 'blue', 'brown', 'beige', 'burgundy'],
        C: ['cyan', 'crimson', 'coral', 'cream'],
        D: ['dark blue', 'dark green'],
        E: ['emerald'],
        F: ['fuchsia'],
        G: ['green', 'gold', 'grey'],
        H: ['hot pink'],
        I: ['indigo', 'ivory'],
        J: ['jade'],
        K: ['khaki'],
        L: ['lavender', 'lime', 'lilac'],
        M: ['maroon', 'magenta', 'mint'],
        N: ['navy'],
        O: ['orange', 'olive'],
        P: ['pink', 'purple', 'peach'],
        Q: ['quartz'],
        R: ['red', 'rose', 'ruby'],
        S: ['silver', 'scarlet', 'sky blue'],
        T: ['teal', 'turquoise', 'tan'],
        U: ['ultramarine'],
        V: ['violet'],
        W: ['white'],
        X: ['xanthic'],
        Y: ['yellow'],
        Z: ['zinnwaldite'],
    },
    professions: {
        A: ['accountant', 'actor', 'architect', 'artist', 'astronaut', 'athlete', 'attorney'],
        B: ['baker', 'banker', 'barber', 'biologist', 'botanist'],
        C: ['carpenter', 'chef', 'chemist', 'coach', 'consultant'],
        D: ['dancer', 'dentist', 'designer', 'developer', 'doctor', 'driver'],
        E: ['economist', 'editor', 'educator', 'engineer'],
        F: ['farmer', 'firefighter', 'fisherman'],
        G: ['geologist', 'graphic designer'],
        H: ['historian', 'hairdresser'],
        I: ['illustrator', 'inspector'],
        J: ['journalist', 'judge'],
        K: ['kindergarten teacher'],
        L: ['lawyer', 'lecturer', 'librarian'],
        M: ['manager', 'mechanic', 'model', 'musician'],
        N: ['nurse', 'nutritionist'],
        O: ['officer', 'optician'],
        P: ['painter', 'pharmacist', 'photographer', 'pilot', 'plumber', 'politician', 'professor'],
        Q: ['quality analyst'],
        R: ['receptionist', 'researcher'],
        S: ['sailor', 'scientist', 'singer', 'soldier', 'surgeon'],
        T: ['teacher', 'technician', 'therapist', 'trader'],
        U: ['umpire'],
        V: ['veterinarian'],
        W: ['waiter', 'writer'],
        X: ['xylophonist'],
        Y: ['yoga instructor'],
        Z: ['zoologist'],
    },
};

for (const [category, grouped] of Object.entries(data)) {
    const outputPath = `./constants/dictionary/${category}.json`;
    fs.writeFileSync(outputPath, JSON.stringify(grouped, null, 2));
    const total = Object.values(grouped).reduce((s, arr) => s + arr.length, 0);
    console.log(`✅ ${category}.json created — ${total} words`);
}

console.log('\n🎉 All remaining dictionaries generated!');